### ISSUE TITLE
Bug in cron.js implementation

### ISSUE THREAD

**Issue by cv711** [redsift/scrumbot#2]
Could not compute DAG: node#3 (Hourly Cron): Cannot read property 'tz' of null stack:TypeError: Cannot read property 'tz' of null
   at module.exports (/run/sandbox/sift/server/cron.js:46:31)
   at Socket.<anonymous> (/usr/bin/redsift/run.js:67:13)
   at emitOne (events.js:96:13)
   at Socket.emit (events.js:188:7)
   at readableAddChunk (_stream_readable.js:172:18)
   at Socket.Readable.push (_stream_readable.js:130:10)
   at Socket._receive (/usr/bin/redsift/node_modules/nanomsg/lib/index.js:198:8)
   at Socket.<anonymous> (/usr/bin/redsift/node_modules/nanomsg/lib/index.js:212:24)],

**Comment by mkarliner** [comment]
I've checked in a fix that sets settings back to default if cron receives a null record, but I still can't see a plausible way this happens, and I haven't been able to replicate this myself to test.

**Comment by deepakprabhakara** [comment]
I'll check the cron jobs.

**Comment by deepakprabhakara** [comment]
Fixed in https://github.com/redsift/scrumbot/commit/7f71b4b0a47cfebe766f163f9092f5f6f051e0d2
